// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvssmnsdlepbjshsitnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2c3NtbnNkbGVwYmpzaHNpdG5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODk4NjcsImV4cCI6MjA2Mzc2NTg2N30.-WBM_uB2KmHcVnJAFNIm2bGMGJHjDO2EnchslgM-CRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);